//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_project.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;
    public partial class MOVIES
    {
		[Key]
		public int ID { get; set; }
		[DisplayName("Movie Name:")]
		[Required]
		public string NAME { get; set; }
		[DisplayName("Price:")]
		[Range(0, 99.99)]
		[Required]
		public double PRICE { get; set; }
		[DisplayName("Genre:")]
		[Required]
		public string GENRE { get; set; }
		[DisplayName("Age Limitation:")]
		public int AGE_LIMITAION { get; set; }
		[DisplayName("Attach a Picture:")]
		[Required]
		public string PicturePath { get; set; }
		public HttpPostedFileBase PictureFile { get; set; }
		[DisplayName("Movie Last Date:")]
		[Required]
		public System.DateTime LASTDATE { get; set; }
		public int AmountOfTime { get; set; }
		[Required]
		[DisplayName("Current Sale %:")]
		public int Sale { get; set; }
		
		public int? newSale { get; set; }
	}
}
