//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_project.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    public partial class Orders
    {
        [DisplayName("Hall Number:")]
        public int HallNumber { get; set; }
        [DisplayName("Date:")]
        public System.DateTime Date { get; set; }
        [DisplayName("From:")]
        public System.TimeSpan FromTime { get; set; }
        [DisplayName("To:")]
        public System.TimeSpan ToTime { get; set; }
        [DisplayName("Line:")]
        public int Line { get; set; }
        [DisplayName("Chair:")]
        public int Chair { get; set; }
        [DisplayName("Movie:")]
        public string Movie { get; set; }

        [StringLength(9,MinimumLength =9, ErrorMessage = "ID need to be 9 characters")]
        [RegularExpression("^([0-9 .&'-]+)$", ErrorMessage = "Invalid ID")]
        [Required(ErrorMessage = "ID is required")]
        public string PersonId { get; set; }
        [StringLength(10)]
        [RegularExpression("^([a-zA-Z .&'-]+)$", ErrorMessage = "Invalid First Name")]
        [Required(ErrorMessage = "First Name is required")]
        public string FirstName { get; set; }
        [RegularExpression("^([a-zA-Z .&'-]+)$", ErrorMessage = "Invalid Last Name")]
        [Required(ErrorMessage = "Last Name is required")]
        [StringLength(20)]
        public string LastName { get; set; }
        [DisplayName("Price:")]
        public double Price { get; set; }
        
        public int OrderId { get; set; }

        
        
    }
}
